const STYLE_LINK_CARD_CLASS_NAME = 'link-card';
const STYLE_LINK_CARD_INFO_CLASS_NAME = 'link-card-info';
const STYLE_LINK_CARD_TIMESTAMP_BAR_CLASS_NAME = 'link-card-timestamp-bar';
const STYLE_TIMESTAMP_CLASS_NAME = 'timestamp';
const STYLE_LINK_CARD_DESCRIPTION_CLASS_NAME = 'link-card-description';
const STYLE_LINK_CARD_CREATED_CLASS_NAME = 'link-card-created';
const STYLE_THUMBNAIL_CONTAINER_CLASS_NAME = 'thumbnail-container';
const STYLE_THUMBNAIL_CLASS_NAME = 'thumbnail';
const STYLE_KEBAB_BUTTON = 'kebab-button';
const STYLE_DROPDOWN_LIST = 'dropdown-list';
const STYLE_DROPDOWN_ITEM = 'dropdown-item';

export {
  STYLE_LINK_CARD_CLASS_NAME,
  STYLE_LINK_CARD_INFO_CLASS_NAME,
  STYLE_LINK_CARD_TIMESTAMP_BAR_CLASS_NAME,
  STYLE_TIMESTAMP_CLASS_NAME,
  STYLE_LINK_CARD_DESCRIPTION_CLASS_NAME,
  STYLE_LINK_CARD_CREATED_CLASS_NAME,
  STYLE_THUMBNAIL_CONTAINER_CLASS_NAME,
  STYLE_THUMBNAIL_CLASS_NAME,
  STYLE_KEBAB_BUTTON,
  STYLE_DROPDOWN_LIST,
  STYLE_DROPDOWN_ITEM,
};
